version: '3'
services:
  frontend:
    build: my-bubble-app/frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    volumes:
      - ./my-bubble-app/frontend/src:/my-bubble-app/frontend/src
    networks:
      - back-to-front-net
  backend:
    build: my-bubble-app/backend
    ports:
      - 3001:3001
    restart: always
    depends_on:
      - database
    networks:
      - db-to-back-net
      - back-to-front-net
  database:
    build: my-bubble-app/database
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./my-bubble-app/database:/my-bubble-app/database
    networks:
      - db-to-back-net
  tests:
    build: my-bubble-app/tests

volumes:
  database-vol:


networks:
  db-to-back-net:
  back-to-front-net:


